@startuml GestionDettes

left to right direction

actor "charge_vente" as AB

rectangle "Admin Boutique GestionDettes" {

    usecase "Lister stats" as ls
    usecase "Lister dette active" as lda

    usecase "Lister article" as la
    usecase "Lister paiement" as lp
    usecase "Rembourser dette" as rd
    usecase "Rechercher client" as rc

    usecase "Sélectionner mode paiement" as smp
    usecase "Ajouter montant" as am

    usecase "se connecter" as sc
    usecase "deconnexion" as D

}

AB --> ls
AB --> lda
AB --> D

ls --> sc

lda --> sc


lda <--  la : <<extend>>
lda <-- lp : <<extend>>
lda <-- rd : <<extend>>
lda <-- rc : <<extend>>

rd ..> smp : <<include>>
rd ..> am : <<include>>


@enduml