@startuml
left to right direction
actor "admin" as A

rectangle "vente"{

    usecase "lister statistiques" as LS 
    usecase "voir encaissements" as VE 
    usecase "voir en cours clients total" as VECT 
    usecase "voir commandes enregistres" as VCE 
    usecase "enregistrer vente" as EV
    usecase "selectionner client" as SC
    usecase "selectionner article" as SA
    usecase "saisir quantite" as SQ
    usecase "se connecter" as SE
    
    usecase "selectionner mode reglement" as SMR
    usecase "saisir montant versement" as SMV
    usecase "lister commandes" as LC
    usecase "voir lignes" as VL

}


A-> LS
A-> EV
A-> LC
A-> SE
EV ..> SC :<<include>>
EV ..> SA :<<include>>
EV ..> SMR :<<include>>
EV ..> SMV :<<include>>
SA ..> SQ :<<include>>
LS <.. VE:<<extend>>
LS <.. VECT:<<extend>>
LS <.. VCE:<<extend>>
LC <.. VL:<<extend>>

@enduml